// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pwnd_c_01
CharacterVector pwnd_c_01();
RcppExport SEXP rpwnd_pwnd_c_01() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(pwnd_c_01());
    return rcpp_result_gen;
END_RCPP
}
